version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

  backend:
    build:
      context: ./backend
    ports:
      - "9000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 1G

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
